version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: Brazil/East
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: activerecord
    versions:
    - 6.0.3.5
    - 6.0.3.6
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2.1
    - 6.1.3
  - dependency-name: actionpack
    versions:
    - 6.0.3.5
